// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package writer_test

import (
	"strings"
	"testing"
	"time"

	"go.thesmos.sh/eidos/writer"
)

func TestHeader_Render(t *testing.T) {
	t.Parallel()

	t.Run("renders DO NOT EDIT line first with the supplied comment prefix", func(t *testing.T) {
		t.Parallel()
		h := writer.Header{Timestamp: time.Date(2026, 5, 11, 14, 23, 11, 0, time.UTC)}
		got := h.Render("// ")
		if !strings.HasPrefix(got, "// Code generated by eidos. DO NOT EDIT.\n") {
			t.Fatalf("first line should announce generation; got %q", got)
		}
	})

	t.Run("sorts the Plugins list alphabetically regardless of input order", func(t *testing.T) {
		t.Parallel()
		h := writer.Header{Plugins: []string{"c", "a", "b"}}
		got := h.Render("// ")
		if !strings.Contains(got, "Plugins: a, b, c") {
			t.Fatalf("plugins should render sorted; got %q", got)
		}
	})

	t.Run("sorts the Sources list alphabetically", func(t *testing.T) {
		t.Parallel()
		h := writer.Header{Sources: []string{"z", "a", "m"}}
		got := h.Render("// ")
		if !strings.Contains(got, "Sources: a, m, z") {
			t.Fatalf("sources should render sorted; got %q", got)
		}
	})

	t.Run("omits empty Command and Sources lines", func(t *testing.T) {
		t.Parallel()
		got := writer.Header{}.Render("// ")
		if strings.Contains(got, "Command:") || strings.Contains(got, "Sources:") {
			t.Fatalf("empty fields should not render: %q", got)
		}
	})

	t.Run("renders the Command line when set", func(t *testing.T) {
		t.Parallel()
		got := writer.Header{Command: "eidos run ./..."}.Render("// ")
		if !strings.Contains(got, "Command: eidos run ./...") {
			t.Fatalf("Command should render: %q", got)
		}
	})

	t.Run("renders Timestamp as RFC 3339 UTC", func(t *testing.T) {
		t.Parallel()
		h := writer.Header{Timestamp: time.Date(2026, 5, 11, 14, 23, 11, 0, time.FixedZone("anywhere", 3600))}
		got := h.Render("// ")
		if !strings.Contains(got, "Generated: 2026-05-11T13:23:11Z") {
			t.Fatalf("timestamp should normalise to UTC; got %q", got)
		}
	})

	t.Run("omits Timestamp line when zero", func(t *testing.T) {
		t.Parallel()
		got := writer.Header{}.Render("// ")
		if strings.Contains(got, "Generated:") {
			t.Fatalf("zero timestamp should not render: %q", got)
		}
	})

	t.Run("works with a non-Go comment prefix", func(t *testing.T) {
		t.Parallel()
		got := writer.Header{}.Render("# ")
		if !strings.HasPrefix(got, "# Code generated") {
			t.Fatalf("comment prefix should be configurable; got %q", got)
		}
	})

	t.Run("ends with a trailing blank line", func(t *testing.T) {
		t.Parallel()
		got := writer.Header{}.Render("// ")
		if !strings.HasSuffix(got, "\n\n") {
			t.Fatalf("header should end with a blank line; got %q", got)
		}
	})
}

func TestFooter(t *testing.T) {
	t.Parallel()

	t.Run("renders an eidos:provenance line with a SHA-256 hex hash", func(t *testing.T) {
		t.Parallel()
		got := writer.Footer([]byte("hello"), "// ")
		// SHA-256 of "hello" is 2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824.
		if !strings.Contains(got, "// eidos:provenance sha256:") {
			t.Fatalf("footer should include the provenance marker; got %q", got)
		}
		if !strings.Contains(got, "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824") {
			t.Fatalf("footer hash should match SHA-256 of body; got %q", got)
		}
	})

	t.Run("identical bodies produce identical footers", func(t *testing.T) {
		t.Parallel()
		a := writer.Footer([]byte("same"), "// ")
		b := writer.Footer([]byte("same"), "// ")
		if a != b {
			t.Fatalf("footer should be deterministic; got %q vs %q", a, b)
		}
	})

	t.Run("different bodies produce different hashes", func(t *testing.T) {
		t.Parallel()
		a := writer.Footer([]byte("aaa"), "// ")
		b := writer.Footer([]byte("bbb"), "// ")
		if a == b {
			t.Fatalf("different bodies should hash differently; got identical %q", a)
		}
	})

	t.Run("works with a non-Go comment prefix", func(t *testing.T) {
		t.Parallel()
		got := writer.Footer([]byte("hi"), "# ")
		if !strings.HasPrefix(got, "# eidos:provenance ") {
			t.Fatalf("comment prefix should be configurable; got %q", got)
		}
	})
}
