// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package writer

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"slices"
	"strings"
	"time"
)

// Header carries the metadata the generated-file header renders:
// the source patterns the frontends consumed, the participating
// plugin names, the command line the run was invoked with, and a
// generation timestamp. Backends render the Header at the top of
// every output file so consumers can attribute generated code back
// to its origin.
//
// Plugin and Source slices are sorted alphabetically at render
// time so the rendered header is deterministic regardless of
// insertion order.
type Header struct {
	// Plugins is the list of plugin names that participated in
	// the run. Rendered sorted.
	Plugins []string

	// Sources is the list of input patterns or files the
	// frontends consumed. Rendered sorted.
	Sources []string

	// Command is the verbatim command line the run was invoked
	// with (typically "eidos run …"). Empty when the run was
	// triggered programmatically rather than via the CLI.
	Command string

	// Timestamp records when the run produced this file. Rendered
	// as RFC 3339 UTC.
	Timestamp time.Time
}

// Render returns the header lines as a single string with a
// trailing blank line. Every line is prefixed with the supplied
// commentPrefix (e.g. "// " for Go, "# " for Python). The output
// is:
//
//	<prefix>Code generated by eidos. DO NOT EDIT.
//	<prefix>Plugins: a, b, c
//	<prefix>Sources: x, y, z
//	<prefix>Command: eidos run …
//	<prefix>Generated: 2026-05-11T14:23:11Z
//	(blank line)
//
// Command and Sources lines are omitted when empty so silent runs
// produce a tidy header.
func (h Header) Render(commentPrefix string) string {
	var b strings.Builder
	line := func(s string) {
		b.WriteString(commentPrefix)
		b.WriteString(s)
		b.WriteByte('\n')
	}
	line("Code generated by eidos. DO NOT EDIT.")
	if plugins := sortedCopy(h.Plugins); len(plugins) > 0 {
		line("Plugins: " + strings.Join(plugins, ", "))
	}
	if sources := sortedCopy(h.Sources); len(sources) > 0 {
		line("Sources: " + strings.Join(sources, ", "))
	}
	if h.Command != "" {
		line("Command: " + h.Command)
	}
	if !h.Timestamp.IsZero() {
		line("Generated: " + h.Timestamp.UTC().Format(time.RFC3339))
	}
	b.WriteByte('\n')
	return b.String()
}

// Footer renders the per-file provenance trailer. The hash is the
// SHA-256 hex digest of the supplied body bytes prefixed with
// "sha256:", embedded after the supplied commentPrefix so the
// output looks like:
//
//	<prefix>eidos:provenance sha256:abcdef…
//
// Two runs of the same pipeline against the same inputs produce
// identical body bytes and so identical footers; downstream
// tooling uses the trailer to verify generated files haven't been
// hand-edited.
func Footer(body []byte, commentPrefix string) string {
	sum := sha256.Sum256(body)
	return fmt.Sprintf("%seidos:provenance sha256:%s\n", commentPrefix, hex.EncodeToString(sum[:]))
}

// sortedCopy returns a sorted copy of in. nil and empty in return
// nil unchanged.
func sortedCopy(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	out := make([]string, len(in))
	copy(out, in)
	slices.Sort(out)
	return out
}
