# Generated by `ergon init`. Edit freely; ergon does not re-read this.
#
# Every target is a one-line shell-out to `ergon <subcommand>`.
# `make help` introspects this file for `## comment` annotations
# and prints an aligned list of targets — keep the annotations in
# sync when you add a target.

.PHONY: help bootstrap install fmt license generate build clean \
        lint lint-md tidy check-tidy \
        test test-race test-bench test-fuzz test-coverage \
        bench-baseline bench-regression bench-profile \
        check check-coverage check-uncovered check-mutation check-branch check-vuln \
        release

ERGON ?= ergon

help: ## Show this help (auto-generated from per-target annotations)
	@awk 'BEGIN {FS = ":.*?## "; printf "Targets:\n"} \
		/^[a-zA-Z][a-zA-Z_-]*:.*?## / {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}' \
		$(MAKEFILE_LIST)

bootstrap: ## Install development tools (gofumpt, gci, golangci-lint, govulncheck, ...)
	$(ERGON) bootstrap
install: ## Download + verify module dependencies
	$(ERGON) mod install
fmt: ## Format Go and Markdown sources
	$(ERGON) fmt
license: ## Apply SPDX license headers
	$(ERGON) license
generate: ## Run `go generate ./...` per module + format
	$(ERGON) generate
build: ## Compile every module's source (sanity check)
	$(ERGON) build
clean: ## Remove build and coverage artefacts
	$(ERGON) clean

lint: ## Run the full lint suite (vet + golangci-lint + markdown + license)
	$(ERGON) lint
lint-md: ## Run markdownlint only
	$(ERGON) lint md

tidy: ## Run `go mod tidy` per module
	$(ERGON) mod tidy
check-tidy: ## Fail when `go mod tidy` would change go.mod/go.sum
	$(ERGON) mod verify

test: ## Run `go test` per module with coverage
	$(ERGON) test
test-race: ## Run `go test -race` per module
	$(ERGON) test race
test-bench: ## Run benchmarks per module (no thresholds)
	$(ERGON) test bench
test-fuzz: ## Run every Fuzz target for the configured duration
	$(ERGON) test fuzz
test-coverage: ## Render per-module coverage profiles to HTML
	$(ERGON) test coverage

bench-baseline: ## Pin the current benchmark numbers to bench/baseline.txt
	$(ERGON) bench baseline
bench-regression: ## Fail when a new run regresses against the pinned baseline
	$(ERGON) bench regression
bench-profile: ## Collect CPU+mem pprof artefacts (PATTERN=. PACKAGE=./... MODULE=.)
	$(ERGON) bench profile $(PATTERN) \
		$(if $(MODULE),--module=$(MODULE),) \
		$(if $(PACKAGE),--package=$(PACKAGE),) \
		$(if $(TIME),--time=$(TIME),) $(FLAGS)

check: ## Run the umbrella pre-merge gate (mod, lint, test, coverage, ...)
	$(ERGON) check
check-coverage: ## Enforce per-layer coverage thresholds
	$(ERGON) check coverage
check-uncovered: ## List every uncovered line across the tree (ignores layer config + excludes)
	$(ERGON) check coverage uncovered
check-mutation: ## Run gremlins mutation testing per layer (slow)
	$(ERGON) check mutation
check-branch: ## Run gobco branch-coverage gating per layer (slow)
	$(ERGON) check branch
check-vuln: ## Run govulncheck per module
	$(ERGON) check vuln

release: ## Bump versions and tag (MESSAGE="..." FLAGS=--major)
	$(ERGON) release $(if $(MESSAGE),-m "$(MESSAGE)",) $(FLAGS)

.DEFAULT_GOAL := help
