# Generated by `ergon init`. Edit freely; ergon does not re-read this.

.PHONY: help bootstrap install fmt license lint test test-race test-coverage \
        bench-baseline bench-regression check check-coverage check-vuln \
        build clean release

ERGON ?= ergon

help:
	@$(ERGON) help

bootstrap:        ; $(ERGON) bootstrap
install:          ; $(ERGON) mod install
fmt:              ; $(ERGON) fmt
license:          ; $(ERGON) license
generate:         ; $(ERGON) generate
build:            ; $(ERGON) build
clean:            ; $(ERGON) clean

lint:             ; $(ERGON) lint
lint-md:          ; $(ERGON) lint md

tidy:             ; $(ERGON) mod tidy
check-tidy:       ; $(ERGON) mod verify

test:             ; $(ERGON) test
test-race:        ; $(ERGON) test race
test-bench:       ; $(ERGON) test bench
test-fuzz:        ; $(ERGON) test fuzz
test-coverage:    ; $(ERGON) test coverage

bench-baseline:   ; $(ERGON) bench baseline
bench-regression: ; $(ERGON) bench regression

check:            ; $(ERGON) check
check-coverage:   ; $(ERGON) check coverage
check-vuln:       ; $(ERGON) check vuln

release:          ; $(ERGON) release $(if $(MESSAGE),-m "$(MESSAGE)",) $(FLAGS)

.DEFAULT_GOAL := help
