// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang_test

import (
	"go/parser"
	"go/token"
	"testing"

	"go.thesmos.sh/eidos/frontend/golang"
)

// TestIsGeneratedFile drives the file-comment predicate the frontend
// uses to skip its own outputs on re-runs. Every accept / reject
// shape the canonical marker pattern recognises has a case here.
func TestIsGeneratedFile(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "canonical eidos header line",
			src:  "// Code generated by eidos. DO NOT EDIT.\n\npackage gen\n",
			want: true,
		},
		{
			name: "stringer-shape header with semicolon separator",
			src:  "// Code generated by \"stringer -type=Status\"; DO NOT EDIT.\n\npackage gen\n",
			want: true,
		},
		{
			name: "multi-line preamble with header below copyright",
			src:  "// Copyright 2026 Acme.\n// SPDX-License-Identifier: MIT\n\n// Code generated by acmegen v1.4. DO NOT EDIT.\n\npackage gen\n",
			want: true,
		},
		{
			name: "leading whitespace tolerated",
			src:  "//   Code generated by eidos. DO NOT EDIT.\n\npackage gen\n",
			want: true,
		},
		{
			name: "marker missing the do-not-edit clause is hand-authored",
			src:  "// Code generated by eidos for reference.\n\npackage gen\n",
			want: false,
		},
		{
			name: "marker that lives below the package clause is ignored",
			src:  "package gen\n\n// Code generated by eidos. DO NOT EDIT.\n",
			want: false,
		},
		{
			name: "plain hand-authored source",
			src:  "// Package gen does things.\npackage gen\n",
			want: false,
		},
		{
			name: "empty file with only the package clause",
			src:  "package gen\n",
			want: false,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			fset := token.NewFileSet()
			f, err := parser.ParseFile(fset, "fixture.go", tc.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("parser.ParseFile: %v", err)
			}
			if got := golang.IsGeneratedFile(f); got != tc.want {
				t.Fatalf("IsGeneratedFile = %v, want %v\nsource:\n%s", got, tc.want, tc.src)
			}
		})
	}

	t.Run("nil ast.File returns false", func(t *testing.T) {
		t.Parallel()
		if golang.IsGeneratedFile(nil) {
			t.Fatalf("IsGeneratedFile(nil) = true, want false")
		}
	})
}

// TestGeneratedFileFilter_LiveFrontend drives the option through the
// public Load surface: a fixture package whose only file carries the
// generator marker reports zero structs when the default filter
// applies, and one struct when the consumer opts out via
// SkipGeneratedFiles=false.
func TestGeneratedFileFilter_LiveFrontend(t *testing.T) {
	t.Parallel()

	src := "// Code generated by eidos. DO NOT EDIT.\n\npackage gen\n\ntype Probe struct{}\n"

	t.Run("default skips the generated file", func(t *testing.T) {
		t.Parallel()
		pkg := requirePackage(t, map[string]string{"probe.go": src})
		if pkg.StructByName("Probe") != nil {
			t.Fatalf("generated file should be filtered out by default; Probe leaked in")
		}
	})

	t.Run("SkipGeneratedFiles=false includes the file", func(t *testing.T) {
		t.Parallel()
		pkg := requirePackageOpts(
			t,
			map[string]string{"probe.go": src},
			map[string]string{"skip_generated_files": "false"},
		)
		if pkg.StructByName("Probe") == nil {
			t.Fatalf("opt-out should load the generated file's structs")
		}
	})
}
