// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

// Package cli supplies command kernels for the generic operations
// every eidos-based binary needs: run, plan, explain, check, prune,
// version. The package does no argument parsing, owns no
// [flag.FlagSet], and depends on no CLI framework.
//
// # Usage
//
// Each command is a struct holding a typed Config. Consumers
// construct a command, call its `RegisterFlags(fs)` method to bind
// the flags into the Config fields via stdlib `flag`, parse the
// supplied args, then call [Command.Execute]:
//
//	cmd := &cli.RunCommand{
//	    Config: cli.RunConfig{Plugins: []plugin.Plugin{repogen.New(), mockgen.New()}},
//	}
//	fs := flag.NewFlagSet("run", flag.ContinueOnError)
//	cmd.RegisterFlags(fs)
//	_ = fs.Parse(os.Args[2:])
//	cmd.Config.Patterns = fs.Args()
//	os.Exit(cmd.Execute(context.Background(), env))
//
// # Embedding model
//
// The primary use case is embedding: downstream binaries import
// `cli`, hardcode a brand identifier via [Env.Brand], register
// their static plugin slice, and dispatch to the appropriate
// command. The reference binary `cmd/eidos/` shows the pattern;
// downstream consumers copy it and substitute their plugin set.
//
// # Brand
//
// [Env.Brand] is the load-bearing identity. It drives the rendered
// header marker (`// Code generated by <brand>. DO NOT EDIT.`) and
// the footer (`// <brand>:provenance <hash>`), and computes the
// default paths for project-local state:
//
//   - Config file discovery: `.<brand>.yaml`, walked up from Env.Workdir.
//   - Manifest: `<Env.Workdir>/.<brand>/manifest.json`.
//   - Cache: `<Env.Workdir>/.<brand>/cache/`.
//
// Consumers set the brand once at program start, never via CLI flag
// or config file.
//
// # Exit codes
//
// Every command returns one of:
//
//   - [ExitOK] (0): success.
//   - [ExitUserError] (1): bad config, missing plugin, invalid flag
//     combination, unresolvable selector.
//   - [ExitPipelineError] (2): pipeline ran but produced Error
//     diagnostics.
//   - [ExitInternalError] (3): recovered from an unexpected panic.
//   - [ExitCacheVerifyFailed] (4): `run --verify-cache` mismatch.
//   - [ExitCheckDrift] (5): `check` detected drift against on-disk
//     state.
//
// Commands never panic out — panics are recovered into [ExitInternalError]
// with a structured diagnostic written to [Env.Diag].
package cli
