// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package cli_test

import (
	"encoding/json"
	"errors"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"go.thesmos.sh/eidos/cli"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/manifest"
	"go.thesmos.sh/eidos/plugin"
)

// seedStaleFile writes a file with the canonical generated-by
// marker line and seeds the prev manifest with a matching entry.
// Used by every prune-test stanza that needs a "previously
// generated, no longer claimed" candidate on disk.
func seedStaleFile(
	t *testing.T,
	workdir, brand, dir, name string,
) (path string, target emit.Target) {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(workdir, dir), 0o750); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	body := []byte("// Code generated by " + brand + ". DO NOT EDIT.\npackage x\n")
	path = filepath.Join(workdir, dir, name)
	if err := os.WriteFile(path, body, 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	return path, emit.Target{Dir: dir, Filename: name, Package: "x"}
}

// writePrevManifest writes a previous-run manifest at the
// brand-derived manifest path so the prune command finds it.
func writePrevManifest(t *testing.T, env *cli.Env, targets ...emit.Target) {
	t.Helper()
	stateDir := env.StateDir()
	if err := os.MkdirAll(stateDir, 0o750); err != nil {
		t.Fatalf("mkdir state: %v", err)
	}
	m := manifest.New("prev-run-id")
	m.Brand = env.Brand
	for _, tgt := range targets {
		m.Add(
			manifest.Output{
				Target:  tgt,
				Plugins: []manifest.PluginAttribution{{Name: "seedgen"}},
				Hash:    "sha256:dummy",
			},
		)
	}
	if err := manifest.Write(env.ManifestPath(), m); err != nil {
		t.Fatalf("write prev manifest: %v", err)
	}
}

// TestPruneCommand_DeletesStaleWithMarker covers the happy path:
// a file claimed by the previous manifest, no longer claimed by
// the current run, with the canonical generated marker — gets
// deleted.
func TestPruneCommand_DeletesStaleWithMarker(t *testing.T) {
	t.Parallel()

	t.Run("file with generated marker is deleted", func(t *testing.T) {
		t.Parallel()
		env, stdout, _ := freshEnv(t, "eidos")
		path, target := seedStaleFile(t, env.Workdir, env.Brand, "out", "stale.go")
		writePrevManifest(t, env, target)
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitOK {
			t.Fatalf("Execute = %d, want ExitOK", code)
		}
		if _, err := os.Stat(path); !errors.Is(err, os.ErrNotExist) {
			t.Fatalf("stale file should be deleted; stat err=%v", err)
		}
		if !strings.Contains(stdout.String(), "deleted:") {
			t.Fatalf("expected deletion line in stdout; got %q", stdout.String())
		}
	})
}

// TestPruneCommand_SkipsWithoutMarker covers the safety guard:
// a file the manifest claims but whose first line lacks the
// generated marker (someone manually edited it) is NOT deleted.
func TestPruneCommand_SkipsWithoutMarker(t *testing.T) {
	t.Parallel()

	t.Run("file without generated marker survives prune", func(t *testing.T) {
		t.Parallel()
		env, stdout, _ := freshEnv(t, "eidos")
		dir := filepath.Join(env.Workdir, "out")
		if err := os.MkdirAll(dir, 0o750); err != nil {
			t.Fatalf("mkdir: %v", err)
		}
		path := filepath.Join(dir, "edited.go")
		// No generated marker — the file appears human-authored.
		body := []byte("package x\n\nfunc Hello() {}\n")
		if err := os.WriteFile(path, body, 0o600); err != nil {
			t.Fatalf("write fixture: %v", err)
		}
		writePrevManifest(t, env, emit.Target{Dir: "out", Filename: "edited.go", Package: "x"})
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitOK {
			t.Fatalf("Execute = %d, want ExitOK", code)
		}
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("file without marker should survive; got %v", err)
		}
		if !strings.Contains(stdout.String(), "skipped") {
			t.Fatalf("expected skip count in stdout; got %q", stdout.String())
		}
	})
}

// TestPruneCommand_DryRunDoesNotDelete covers the DryRun mode:
// the command reports planned deletions without performing them.
func TestPruneCommand_DryRunDoesNotDelete(t *testing.T) {
	t.Parallel()

	t.Run("DryRun reports would-delete without removing", func(t *testing.T) {
		t.Parallel()
		env, stdout, _ := freshEnv(t, "eidos")
		path, target := seedStaleFile(t, env.Workdir, env.Brand, "out", "candidate.go")
		writePrevManifest(t, env, target)
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			DryRun: true,
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitOK {
			t.Fatalf("Execute = %d, want ExitOK", code)
		}
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("DryRun must not delete; got %v", err)
		}
		out := stdout.String()
		if !strings.Contains(out, "would delete:") {
			t.Fatalf("expected would-delete line; got %q", out)
		}
		if !strings.Contains(out, "dry-run") {
			t.Fatalf("expected dry-run summary; got %q", out)
		}
	})
}

// TestPruneCommand_NoPrevManifest covers the no-op path: with no
// previous manifest, prune has nothing to diff against; the
// command exits cleanly with a zero-count summary.
func TestPruneCommand_NoPrevManifest(t *testing.T) {
	t.Parallel()

	t.Run("no previous manifest is treated as nothing to prune", func(t *testing.T) {
		t.Parallel()
		env, stdout, _ := freshEnv(t, "eidos")
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitOK {
			t.Fatalf("Execute = %d, want ExitOK", code)
		}
		if !strings.Contains(stdout.String(), "0 deleted") {
			t.Fatalf("expected zero-count summary; got %q", stdout.String())
		}
	})
}

// TestPruneCommand_ConfigError covers the user-error path: a
// config naming a missing plugin exits ExitUserError before any
// deletion happens.
func TestPruneCommand_ConfigError(t *testing.T) {
	t.Parallel()

	t.Run("missing plugin exits ExitUserError", func(t *testing.T) {
		t.Parallel()
		env, _, stderr := freshEnv(t, "eidos")
		cfg := cli.DefaultConfig()
		cfg.Plugins = []cli.ConfigPlugin{{Name: "ghost"}}
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			File: cfg,
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitUserError {
			t.Fatalf("Execute = %d, want ExitUserError", code)
		}
		if !strings.Contains(stderr.String(), "ghost") {
			t.Fatalf("stderr should name the missing plugin; got %q", stderr.String())
		}
	})
}

// TestPruneCommand_PreservesManifestJSON is a sanity probe: after
// prune, the new manifest on disk is valid JSON. Catches
// serialisation regressions that would render the manifest
// unreadable on the next prune.
func TestPruneCommand_PreservesManifestJSON(t *testing.T) {
	t.Parallel()

	t.Run("post-prune manifest is valid JSON", func(t *testing.T) {
		t.Parallel()
		env, _, _ := freshEnv(t, "eidos")
		_, target := seedStaleFile(t, env.Workdir, env.Brand, "out", "stale.go")
		writePrevManifest(t, env, target)
		cmd := &cli.PruneCommand{Config: cli.PruneConfig{
			Plugins: []plugin.Plugin{
				stubFrontend{name: "fe"},
				stubBackend{name: "be", lang: "stub"},
			},
		}}
		if code := cmd.Execute(t.Context(), env); code != cli.ExitOK {
			t.Fatalf("Execute = %d, want ExitOK", code)
		}
		raw, err := os.ReadFile(env.ManifestPath())
		if err != nil {
			t.Fatalf("read manifest: %v", err)
		}
		var v any
		if err := json.Unmarshal(raw, &v); err != nil {
			t.Fatalf("manifest not valid JSON after prune: %v\n%s", err, raw)
		}
	})
}

// TestPruneCommand_RegisterFlags_Routing pins the routing-flag
// wiring on PruneCommand — parsed values land on
// [cli.PruneConfig.Routing].
func TestPruneCommand_RegisterFlags_Routing(t *testing.T) {
	t.Parallel()

	t.Run("Routing flags parse onto PruneCommand.Config.Routing", func(t *testing.T) {
		t.Parallel()
		var cmd cli.PruneCommand
		fs := flag.NewFlagSet("prune", flag.ContinueOnError)
		cmd.RegisterFlags(fs)
		assertRoutingFlagsParse(t, fs, &cmd.Config.Routing)
	})
}
