// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package cli

import (
	"bufio"
	"context"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"go.thesmos.sh/eidos/core/position"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/manifest"
	"go.thesmos.sh/eidos/pipeline"
	"go.thesmos.sh/eidos/plugin"
)

// PruneConfig holds the inputs for [PruneCommand]. The command
// runs the pipeline, then deletes files claimed by the previous
// manifest that the current run no longer claims — gated by a
// first-line marker check so manually-edited files survive.
type PruneConfig struct {
	// File is the loaded config.
	File *Config

	// Plugins is the consumer's static plugin universe.
	Plugins []plugin.Plugin

	// DryRun reports the planned deletions without applying them.
	// Useful for CI gates that want to surface "this would have
	// deleted N files" before the destructive run.
	DryRun bool

	// DiagFormat selects the diagnostic rendering format used for
	// pipeline diagnostics.
	DiagFormat DiagFormat

	// Verbose / Quiet propagate to the diagnostic filter.
	Verbose bool
	Quiet   bool
}

// PruneCommand implements the `prune` semantic per the CLI spec.
// Returns:
//
//   - [ExitOK] when prune completes (including DryRun reports).
//   - [ExitUserError] on configuration faults.
//   - [ExitPipelineError] when the pipeline run emitted Error
//     diagnostics.
//   - [ExitInternalError] on a recovered panic.
type PruneCommand struct{ Config PruneConfig }

// RegisterFlags binds [PruneCommand]'s flags into fs.
func (c *PruneCommand) RegisterFlags(fs *flag.FlagSet) {
	fs.Var(&c.Config.DiagFormat, FlagDiagFormat, UsageDiagFormat)
	fs.BoolVar(&c.Config.Verbose, FlagVerbose, false, UsageVerbose)
	fs.BoolVar(&c.Config.Quiet, FlagQuiet, false, UsageQuiet)
	fs.BoolVar(&c.Config.DryRun, FlagDryRun, false, UsageDryRun)
}

// Execute reads the previous manifest, runs the pipeline (which
// overwrites the manifest with current outputs), diffs the two,
// and deletes files no longer claimed — subject to the
// marker-line guard.
func (c *PruneCommand) Execute(ctx context.Context, env *Env) (exit int) {
	defer recoverInto(env, &exit)

	cfg := c.Config.File
	if cfg == nil {
		cfg = DefaultConfig()
	}
	prevPath := manifestPath(env, cfg)
	prev := readManifestSilent(prevPath)

	p, err := buildPipeline(env, cfg, c.Config.Plugins, pipelineOverride{Verbose: c.Config.Verbose})
	if err != nil {
		writeErr(env, "%v", err)
		return ExitUserError
	}
	runErr := p.Run(ctx, patternsFromConfig(cfg)...)
	rerr := RenderDiagnostics(env.Stderr, p.Diag(), c.Config.DiagFormat, c.Config.Verbose, c.Config.Quiet)
	if rerr != nil {
		writeErr(env, "%v", rerr)
	}
	if runErr != nil && !errors.Is(runErr, pipeline.ErrRunHadErrors) {
		writeErr(env, "%v", runErr)
		return ExitPipelineError
	}

	current := readManifestSilent(prevPath)
	stale := manifest.Prune(prev, current)
	return c.applyPrune(env, stale, runErr)
}

// applyPrune walks the stale targets, guards each delete on the
// first-line marker, and reports the result. Returns the
// appropriate exit code.
func (c *PruneCommand) applyPrune(env *Env, stale []emit.Target, runErr error) int {
	deleted := 0
	skipped := 0
	for _, t := range stale {
		fullPath := filepath.Join(env.Workdir, t.Dir, t.Filename)
		ok, err := hasGeneratedMarker(fullPath, env.Brand)
		if err != nil {
			if env.Diag != nil {
				env.Diag.For("pipeline.prune").Warnf(position.Pos{File: fullPath}, "%v", err)
			}
			skipped++
			continue
		}
		if !ok {
			if env.Diag != nil {
				env.Diag.For("pipeline.prune").Infof(position.Pos{File: fullPath},
					"skipped: no `// Code generated by %s.` marker — refusing to delete a manually-edited file", env.Brand)
			}
			skipped++
			continue
		}
		if c.Config.DryRun {
			fmt.Fprintf(env.Stdout, "would delete: %s\n", fullPath)
			deleted++
			continue
		}
		if err := os.Remove(fullPath); err != nil {
			writeErr(env, "delete %s: %v", fullPath, err)
			skipped++
			continue
		}
		fmt.Fprintf(env.Stdout, "deleted: %s\n", fullPath)
		deleted++
	}
	if c.Config.DryRun {
		fmt.Fprintf(env.Stdout, "prune dry-run: %d would-delete, %d skipped\n", deleted, skipped)
	} else {
		fmt.Fprintf(env.Stdout, "prune: %d deleted, %d skipped\n", deleted, skipped)
	}
	if errors.Is(runErr, pipeline.ErrRunHadErrors) {
		return ExitPipelineError
	}
	return ExitOK
}

// readManifestSilent reads a manifest from path, returning nil
// when the file is missing or malformed. Prune treats a missing
// previous manifest as "nothing to prune"; a malformed previous
// manifest is logged via the underlying I/O failure but doesn't
// stop the run.
func readManifestSilent(path string) *manifest.Manifest {
	if path == "" {
		return nil
	}
	m, err := manifest.Read(path)
	if err != nil {
		return nil
	}
	return m
}

// hasGeneratedMarker returns true when the first non-empty line of
// the file at path starts with `// Code generated by <brand>.`.
// The marker is the conventional Go-generator signal the prune
// guard checks before deleting a file claimed by the previous
// manifest. A missing file is treated as "no marker" — the file
// is gone, nothing to delete.
func hasGeneratedMarker(path, brand string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, fmt.Errorf("cli: open for marker check %s: %w", path, err)
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	prefix := fmt.Sprintf("// Code generated by %s.", brand)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		return strings.HasPrefix(line, prefix), nil
	}
	if err := scanner.Err(); err != nil {
		return false, fmt.Errorf("cli: scan marker line %s: %w", path, err)
	}
	return false, nil
}
