// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package plugin

import (
	"go.thesmos.sh/eidos/core/diag"
	"go.thesmos.sh/eidos/sink"
	"go.thesmos.sh/eidos/store"
)

// Backend is the role for plugins that render emit entities to a
// target language and write the result through a [sink.Sink].
// Exactly one Backend runs per pipeline (the builder rejects zero
// or multiple Backends).
//
// Render groups emit entities by their [emit.Target], renders one
// file per group through the language-specific templates, finalises
// the output (import resolution, formatting), and writes via
// ctx.Sink. Per-file issues attach to ctx.Diag; fatal failures
// return a non-nil error.
type Backend interface {
	Plugin

	// Language returns the target-language identifier — the same
	// string the [TemplateProvider] interface uses to scope
	// templates and func-map extensions ("go", "rust", "ts", …).
	Language() string

	// Render renders the emit entities in ctx.Store.Emit() and
	// writes finalised file content through ctx.Sink.
	Render(ctx *BackendContext) error
}

// BackendContext is the per-run context handed to the [Backend]. It
// supplies the shared store, the diagnostic sink, the destination
// sink, the language identifier (so plugin-supplied template /
// func-map extensions can target it), and the ordered list of
// plugins that participated in the run (so the backend can collect
// template providers and apply overrides in capability topo order).
type BackendContext struct {
	// Store is the shared in-memory database. The backend reads
	// from Store.Emit().
	Store *store.Store

	// Reader is the per-plugin read-tracking handle.
	Reader *store.Reader

	// Diag is the diagnostic sink shared with every plugin in the
	// run.
	Diag *diag.Sink

	// Sink is the destination the backend writes finalised file
	// content through.
	Sink sink.Sink

	// Lang is the target-language identifier the backend renders
	// for. Equal to the value [Backend.Language] returns; mirrored
	// here so plugin-supplied template providers can target it
	// without consulting the Backend implementation directly.
	Lang string

	// Plugins is the full list of plugins that participated in the
	// run, in the order the user registered them. The backend uses
	// this to find every [TemplateProvider] for template merging.
	Plugins []Plugin

	// Ordered is the same plugins as [Plugins], reordered by the
	// pipeline's resolved capability topo. The backend uses this to
	// apply [TemplateProvider.TemplateOverrides] in deterministic
	// order so collisions resolve last-write-wins predictably.
	Ordered []Plugin

	// Command is the literal text the backend stamps into the
	// "Command:" header line. The pipeline sets it to a rendering
	// of `os.Args[1:]` for CLI runs, or "(library)" when invoked
	// programmatically. The empty string means "use os.Args[1:] at
	// render" — useful as a default; tests usually set it
	// explicitly for stable goldens.
	Command string

	// SourcesOverride supplies the literal entries that populate
	// the "Source:" header line, overriding the per-entity origin
	// derivation. Use ["programmatic"] for library callers, or any
	// fixed list for test fixtures that need stable header output.
	// A nil/empty slice leaves the backend to derive sources from
	// each emit entity's [emit.Node.Origin] back-pointer.
	SourcesOverride []string

	// HeaderPrefix lists lines the backend writes at the very top
	// of every rendered file, before the "Code generated by eidos.
	// DO NOT EDIT." marker. Each entry is one line, rendered
	// verbatim (no `// ` prefix added by the backend) and
	// separated from the standard header by a blank line. Library
	// embedders use this slot for project-wide boilerplate such as
	// copyright notices or build-tag constraints (`//go:build …`).
	HeaderPrefix []string

	// HeaderSuffix lists lines the backend writes after the
	// standard header block (after the Source / Plugins / Command
	// lines, before the trailing blank line). Each entry is
	// rendered verbatim. Use for additional project-wide notices
	// or diagnostic metadata that should ride alongside the
	// canonical header content.
	HeaderSuffix []string

	// FooterSuffix lists lines the backend writes after the
	// standard footer (the end-of-generated-content marker and the
	// provenance hash line). Each entry is rendered verbatim. Use
	// for org-specific signing markers or additional trailing
	// metadata.
	FooterSuffix []string

	// Brand is the tool identifier stamped into the header's
	// "Code generated by <Brand>. DO NOT EDIT." marker and the
	// footer's "<Brand>: end of generated content." line. Library
	// embedders set this to their tool's identifier so files
	// generated through eidos appear to be produced by their tool
	// — useful for organizations that build internal generators on
	// top of eidos and want the brand to reflect the wrapper.
	//
	// Empty defaults to "eidos". The substitution preserves
	// compliance with Go's generated-file detection regex
	// (`^// Code generated .* DO NOT EDIT\.$`); any non-empty
	// Brand keeps the file detectable by `gofmt`, linters, and
	// `go generate`-aware tooling.
	Brand string

	// SourceRoot is the base directory paths in the "Source:" header
	// line are made relative to. The renderer strips this prefix
	// from each entity's origin file path and normalises the result
	// to forward slashes — the output stays byte-identical regardless
	// of where on disk the project lives or which OS produced it.
	//
	// [pipeline.Builder.Build] populates this from
	// [pipeline.Builder.WithSourceRoot] when set, otherwise from
	// [os.Getwd] at construction time. The field is rarely empty in
	// practice; the backend falls through to verbatim rendering if it
	// is (Getwd failure, or a caller assembling the context directly).
	SourceRoot string
}
