// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang

import (
	"fmt"
	"slices"
	"strings"

	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/plugin"
)

// renderHeader produces the comment block written at the top of
// every generated file. The standard block carries three semantic
// lines — Source, Plugins, Command — plus the canonical "DO NOT
// EDIT" marker. Library embedders extend the header via
// [plugin.BackendContext.HeaderPrefix] (lines before the marker —
// copyright, build-tag constraints) and [plugin.BackendContext.HeaderSuffix]
// (lines after the standard block — additional notices). Both
// extension slots render their entries verbatim, so callers
// control whether the line is a comment or a build directive. The
// block ends with a trailing blank line so the following `package`
// clause starts cleanly.
//
// Output is deterministic per input: no timestamp, no per-run
// state. Two runs over the same emit graph, the same registered
// plugins, and the same header-config fields produce byte-identical
// headers. Run-context like "when was this generated" lives in
// git history and filesystem mtime, not in the file's bytes.
func renderHeader(ctx *plugin.BackendContext, entities []emit.Node) string {
	var b strings.Builder
	writeLines(&b, ctx.HeaderPrefix)
	if len(ctx.HeaderPrefix) > 0 {
		b.WriteByte('\n')
	}
	fmt.Fprintf(&b, "// Code generated by %s. DO NOT EDIT.\n", brandOf(ctx))
	sources := sourcesFor(ctx, entities)
	plugins := pluginsFor(ctx)
	cmd := strings.TrimSpace(ctx.Command)
	if len(sources) > 0 || plugins != "" || cmd != "" {
		b.WriteString("//\n")
		if len(sources) > 0 {
			fmt.Fprintf(&b, "// Source:    %s\n", strings.Join(sources, ", "))
		}
		if plugins != "" {
			fmt.Fprintf(&b, "// Plugins:   %s\n", plugins)
		}
		if cmd != "" {
			fmt.Fprintf(&b, "// Command:   %s\n", cmd)
		}
	}
	writeLines(&b, ctx.HeaderSuffix)
	b.WriteByte('\n')
	return b.String()
}

// writeLines appends each entry of lines to b, terminated by '\n'.
// Empty slices write nothing. Used by both [renderHeader] and the
// footer wrapper to emit verbatim caller-supplied line blocks.
func writeLines(b *strings.Builder, lines []string) {
	for _, line := range lines {
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

// brandOf returns the tool identifier stamped into the canonical
// "Code generated by <Brand>. DO NOT EDIT." header marker and the
// "<Brand>: end of generated content." footer line. An empty
// [plugin.BackendContext.Brand] defaults to "eidos".
func brandOf(ctx *plugin.BackendContext) string {
	if ctx.Brand == "" {
		return "eidos"
	}
	return ctx.Brand
}

// sourcesFor returns the list of source-path entries the Source:
// header line surfaces. The list is `BackendContext.SourcesOverride`
// when set; otherwise it is the deduplicated, sorted union of every
// supplied entity's [emit.Node.Origin] source-file path. Returns
// nil when nothing surfaces and no override is set — the caller
// omits the Source: line in that case.
func sourcesFor(ctx *plugin.BackendContext, entities []emit.Node) []string {
	if len(ctx.SourcesOverride) > 0 {
		out := make([]string, len(ctx.SourcesOverride))
		copy(out, ctx.SourcesOverride)
		return out
	}
	set := map[string]struct{}{}
	for _, n := range entities {
		origin := n.Origin()
		if origin == nil {
			continue
		}
		file := origin.Pos().File
		if file == "" {
			continue
		}
		set[file] = struct{}{}
	}
	if len(set) == 0 {
		return nil
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

// pluginsFor renders the Plugins: header line content from
// `BackendContext.Plugins`. Each plugin contributes its Name(); if
// the plugin also satisfies [plugin.Versioned] and reports a
// non-empty version, the entry becomes `<name> <version>`. The
// resulting entries are joined by ", " in plugin-registration
// order. Returns the empty string when no plugins are registered —
// the caller omits the Plugins: line in that case.
func pluginsFor(ctx *plugin.BackendContext) string {
	if len(ctx.Plugins) == 0 {
		return ""
	}
	entries := make([]string, 0, len(ctx.Plugins))
	for _, p := range ctx.Plugins {
		entry := p.Name()
		if v, ok := p.(plugin.Versioned); ok {
			if version := strings.TrimSpace(v.Version()); version != "" {
				entry = entry + " " + version
			}
		}
		entries = append(entries, entry)
	}
	return strings.Join(entries, ", ")
}
