// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/plugin"
)

// renderHeader produces the comment block written at the top of
// every generated file. The standard block carries three semantic
// lines — Source, Plugins, Command — plus the canonical "DO NOT
// EDIT" marker. Library embedders extend the header via
// [plugin.BackendContext.HeaderPrefix] (lines before the marker —
// copyright, build-tag constraints) and [plugin.BackendContext.HeaderSuffix]
// (lines after the standard block — additional notices). Both
// extension slots render their entries verbatim, so callers
// control whether the line is a comment or a build directive. The
// block ends with a trailing blank line so the following `package`
// clause starts cleanly.
//
// Output is deterministic per input: no timestamp, no per-run
// state. Two runs over the same emit graph, the same registered
// plugins, and the same header-config fields produce byte-identical
// headers. Run-context like "when was this generated" lives in
// git history and filesystem mtime, not in the file's bytes.
func renderHeader(ctx *plugin.BackendContext, entities []emit.Node) string {
	var b strings.Builder
	writeLines(&b, ctx.HeaderPrefix)
	if len(ctx.HeaderPrefix) > 0 {
		b.WriteByte('\n')
	}
	fmt.Fprintf(&b, "// Code generated by %s. DO NOT EDIT.\n", brandOf(ctx))
	sources := sourcesFor(ctx, entities)
	plugins := pluginsFor(ctx, entities)
	cmd := strings.TrimSpace(ctx.Command)
	if len(sources) > 0 || plugins != "" || cmd != "" {
		b.WriteString("//\n")
		if len(sources) > 0 {
			fmt.Fprintf(&b, "// Source:    %s\n", strings.Join(sources, ", "))
		}
		if plugins != "" {
			fmt.Fprintf(&b, "// Plugins:   %s\n", plugins)
		}
		if cmd != "" {
			fmt.Fprintf(&b, "// Command:   %s\n", cmd)
		}
	}
	writeLines(&b, ctx.HeaderSuffix)
	b.WriteByte('\n')
	return b.String()
}

// writeLines appends each entry of lines to b, terminated by '\n'.
// Empty slices write nothing. Used by both [renderHeader] and the
// footer wrapper to emit verbatim caller-supplied line blocks.
func writeLines(b *strings.Builder, lines []string) {
	for _, line := range lines {
		b.WriteString(line)
		b.WriteByte('\n')
	}
}

// brandOf returns the tool identifier stamped into the canonical
// "Code generated by <Brand>. DO NOT EDIT." header marker and the
// "<Brand>: end of generated content." footer line. An empty
// [plugin.BackendContext.Brand] defaults to "eidos".
func brandOf(ctx *plugin.BackendContext) string {
	if ctx.Brand == "" {
		return "eidos"
	}
	return ctx.Brand
}

// sourcesFor returns the list of source-path entries the Source:
// header line surfaces. The list is [plugin.BackendContext.SourcesOverride]
// when set; otherwise it is the deduplicated, sorted union of every
// supplied entity's [emit.Node.Origin] source-file path.
//
// When entities is non-empty but no entity carries an Origin path
// (a generator omitted provenance threading), the list collapses
// to a single ["unknown"] entry so the Source: line still renders
// — a visible marker that the file's provenance is unattributed
// rather than the line silently disappearing. Returns nil when
// entities is empty and no override is set.
func sourcesFor(ctx *plugin.BackendContext, entities []emit.Node) []string {
	if len(ctx.SourcesOverride) > 0 {
		out := make([]string, len(ctx.SourcesOverride))
		copy(out, ctx.SourcesOverride)
		return out
	}
	set := map[string]struct{}{}
	for _, n := range entities {
		collectOriginPaths(n, ctx.SourceRoot, set)
	}
	if len(set) == 0 {
		if len(entities) == 0 {
			return nil
		}
		return []string{unknownSource}
	}
	out := make([]string, 0, len(set))
	for k := range set {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

// collectOriginPaths records every source-file path attributable to
// n in set. n's own Origin lands first; for [emit.File] entities the
// helper also walks the documented per-file slots (top, bottom, init,
// imports) so a file composed entirely from origin-anchored slot
// contributions (registrygen's per-init Registration is the canonical
// case) still surfaces the contributing source paths in the rendered
// Source: header line.
func collectOriginPaths(n emit.Node, root string, set map[string]struct{}) {
	if n == nil {
		return
	}
	if origin := n.Origin(); origin != nil {
		if file := origin.Pos().File; file != "" {
			set[normalisedSourcePath(file, root)] = struct{}{}
		}
	}
	file, ok := n.(*emit.File)
	if !ok {
		return
	}
	for _, name := range fileSourceWalkSlots {
		slot := file.Slot(name)
		if slot == nil {
			continue
		}
		for _, item := range slot.Items {
			collectOriginPaths(item, root, set)
		}
	}
}

// fileSourceWalkSlots is the documented set of [emit.File] slots
// the Source: header attribution walks. Plugin-defined slot names
// are out of scope — they don't currently carry Origin-bearing items
// the framework knows how to walk, and Source: attribution is
// observability rather than a routing input.
var fileSourceWalkSlots = []string{"top", "bottom", "init", "imports"}

// normalisedSourcePath returns file rewritten for stable rendering:
// when root is set, the path is made relative to it; either way the
// result is normalised to forward slashes so the rendered "Source:"
// header line stays byte-identical across machines, operating
// systems, and project-root layouts.
//
// A file that lives outside root (filepath.Rel returns an error, or
// the result starts with "..") falls back to the original path so
// the rendered header still attributes the source — losing path
// portability rather than silently dropping the attribution.
func normalisedSourcePath(file, root string) string {
	if root != "" {
		if rel, err := filepath.Rel(root, file); err == nil && !strings.HasPrefix(rel, "..") {
			file = rel
		}
	}
	return filepath.ToSlash(file)
}

// unknownSource is the synthetic placeholder the Source: header
// line carries when entities exist but no entity threaded a
// source-file path through its origin. Surfaces the missing
// attribution rather than silently omitting the line — generators
// that should have threaded provenance get a visible reminder in
// every rendered file's header.
const unknownSource = "unknown"

// pluginsFor renders the Plugins: header line content. Only
// plugins that actually contributed entities to this target — read
// from each entity's [emit.Node.SetBy] — appear in the rendered
// list, preserved in [plugin.BackendContext.Plugins] registration
// order. Plugins with a non-empty [plugin.Versioned.Version] render
// as `<name> <version>`; the version is omitted otherwise. The
// frontend and the active backend always appear so consumers can
// identify the language toolchain that produced the file.
//
// When entities carry no SetBy attribution at all (the test-fixture
// case where structs are constructed without the builder), the
// function falls back to the full ctx.Plugins set so historical
// pinning stays stable. Real-pipeline runs always stamp SetBy via
// the builder constructors, so the per-target filter kicks in for
// production output.
//
// Returns the empty string when ctx.Plugins itself is empty.
func pluginsFor(ctx *plugin.BackendContext, entities []emit.Node) string {
	if len(ctx.Plugins) == 0 {
		return ""
	}
	contributed := contributingPluginSet(entities)
	includeAll := len(contributed) == 0
	entries := make([]string, 0, len(ctx.Plugins))
	for _, p := range ctx.Plugins {
		_, isFrontend := p.(plugin.Frontend)
		_, isBackend := p.(plugin.Backend)
		if !includeAll && !isFrontend && !isBackend && !contributed[p.Name()] {
			continue
		}
		entry := p.Name()
		if v, ok := p.(plugin.Versioned); ok {
			if version := strings.TrimSpace(v.Version()); version != "" {
				entry = entry + " " + version
			}
		}
		entries = append(entries, entry)
	}
	return strings.Join(entries, ", ")
}

// contributingPluginSet returns the unique plugin identifiers that
// produced content routed to the current target. Three sources
// participate:
//
//   - The entity's own [emit.Node.SetBy] — top-level decls built
//     through a builder constructor carry the plugin that built
//     them.
//   - Each entity's slot ProvenanceList — cross-cutting weavers
//     (audit-weaver, debug-weaver) contribute via slot items
//     stamped with [emit.Provenance.SetBy] rather than as
//     stand-alone entities.
//   - The same walk recurses into a method-bearing host's methods
//     so a weaver stamping a method's prebody / postbody / return
//     slot still registers in the host entity's contribution set.
//
// The empty string ("unattributed") is dropped so hand-rolled /
// synthetic content does not pollute the set.
func contributingPluginSet(entities []emit.Node) map[string]bool {
	out := map[string]bool{}
	for _, e := range entities {
		collectContributors(e, out)
	}
	return out
}

// collectContributors walks n's own SetBy + any slot provenances
// attached to n into out. Method-bearing hosts (Struct, Interface,
// Alias) recurse into their methods so slot contributions stamped
// inside method bodies flow up.
func collectContributors(n emit.Node, out map[string]bool) {
	if n == nil {
		return
	}
	if name := strings.TrimSpace(n.SetBy()); name != "" {
		out[name] = true
	}
	if host, ok := n.(slotEnumerator); ok {
		for _, slot := range host.SlotsByName() {
			for _, prov := range slot.ProvenanceList {
				if name := strings.TrimSpace(prov.SetBy); name != "" {
					out[name] = true
				}
			}
		}
	}
	switch host := n.(type) {
	case *emit.Struct:
		for _, m := range host.Methods {
			collectContributors(m, out)
		}
	case *emit.Interface:
		for _, m := range host.Methods {
			collectContributors(m, out)
		}
	case *emit.Alias:
		for _, m := range host.Methods {
			collectContributors(m, out)
		}
	}
}

// slotEnumerator is the read-only counterpart of the (unexported)
// slotMap embedded by every emit host. The interface is satisfied
// implicitly by Package / File / Struct / Interface / Method /
// Function / Field / Enum.
type slotEnumerator interface {
	SlotsByName() map[string]*emit.Slot
}
