// Copyright Thesmos B.V. 2026
// SPDX-License-Identifier: MIT

package golang_test

import (
	"strings"
	"testing"

	"go.thesmos.sh/eidos/core/position"
	"go.thesmos.sh/eidos/emit"
	"go.thesmos.sh/eidos/node"
	"go.thesmos.sh/eidos/plugin"
)

// TestHeader_DoNotEditAlways pins the canonical first line that
// linters and `go generate`-aware tooling auto-detect to identify
// generated files.
func TestHeader_DoNotEditAlways(t *testing.T) {
	t.Parallel()

	t.Run("every rendered file leads with the standard marker", func(t *testing.T) {
		t.Parallel()
		body := renderSingleFieldStruct(t, "F", emit.Builtin("int"))
		if !strings.HasPrefix(body, "// Code generated by eidos. DO NOT EDIT.\n") {
			t.Fatalf("output should begin with the DO NOT EDIT marker; got first line:\n%s", firstLine(body))
		}
	})
}

// TestHeader_SourcesOverride covers the explicit-override path:
// callers supply the Source: line content directly via
// [plugin.BackendContext.SourcesOverride], bypassing
// origin-derived sources.
func TestHeader_SourcesOverride(t *testing.T) {
	t.Parallel()

	t.Run("override renders verbatim into the Source line", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.SourcesOverride = []string{"programmatic"}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    programmatic\n") {
			t.Fatalf("body should contain the override; got:\n%s", body)
		}
	})

	t.Run("override with multiple entries joins by ', ' in supplied order", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.SourcesOverride = []string{"b.go", "a.go"}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    b.go, a.go\n") {
			t.Fatalf("override should render in supplied order; got:\n%s", body)
		}
	})
}

// TestHeader_SourcesFromOrigin covers the per-entity origin
// derivation: when no override is set, the backend collects the
// `Origin().Pos().File` of every entity routed to the Target,
// dedupes, and sorts.
func TestHeader_SourcesFromOrigin(t *testing.T) {
	t.Parallel()

	t.Run("entity origin file paths surface in the Source line", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		origin := &node.Struct{
			BaseNode: node.BaseNode{SourcePos: position.Pos{File: "internal/users/user.go"}},
		}
		addEmitPackage(t, ctx, emitPackage("x", &emit.Struct{
			BaseEmit: emit.BaseEmit{OriginNode: origin},
			Name:     "X", Package: "x", Target: target,
			Fields: []*emit.Field{{Name: "F", Type: emit.Builtin("int")}},
		}))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    internal/users/user.go\n") {
			t.Fatalf("entity origin should surface; got:\n%s", body)
		}
	})

	t.Run("multiple entities with distinct origins produce a deduped sorted list", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		// b.go and a.go contribute distinct entities; duplicate
		// b.go entries should not double-count.
		addEmitPackage(t, ctx, emitPackage(
			"x",
			structWithOrigin("X1", "x", target, "b.go"),
			structWithOrigin("X2", "x", target, "a.go"),
			structWithOrigin("X3", "x", target, "b.go"),
		))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    a.go, b.go\n") {
			t.Fatalf("sources should be deduped + sorted; got:\n%s", body)
		}
	})

	t.Run("entities without origin surface the synthetic unknown marker", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		// No origin set — the Source line surfaces the synthetic
		// "unknown" marker so the missing-provenance condition is
		// visible in every rendered file rather than silently
		// omitted.
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    unknown") {
			t.Fatalf("Source line should carry 'unknown' when no origins exist; got:\n%s", body)
		}
	})

	t.Run("SourceRoot relativises absolute origin paths and forward-slashes them", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.SourceRoot = "/home/dev/proj"
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage(
			"x",
			structWithOrigin("X", "x", target, "/home/dev/proj/internal/users/user.go"),
		))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    internal/users/user.go\n") {
			t.Fatalf("SourceRoot should produce repo-relative paths; got:\n%s", body)
		}
	})

	t.Run("SourceRoot leaves out-of-root paths verbatim rather than dropping attribution", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.SourceRoot = "/home/dev/proj"
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		// File outside the root — filepath.Rel would produce a path
		// starting with `..`, signalling the file lives outside the
		// project. The renderer keeps the original path so attribution
		// is preserved.
		addEmitPackage(t, ctx, emitPackage(
			"x",
			structWithOrigin("X", "x", target, "/var/cache/external.go"),
		))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    /var/cache/external.go\n") {
			t.Fatalf("out-of-root path should render verbatim; got:\n%s", body)
		}
	})

	t.Run("File slot items contribute Source attribution", func(t *testing.T) {
		t.Parallel()
		// A file with no per-decl entities — only origin-anchored
		// slot contributions in the `init` slot (the registrygen
		// pattern). The Source: header line walks the file's slots
		// and collects every slot item's Origin so the file's
		// Source attribution surfaces even when the file is
		// composed entirely from slot contributions.
		ctx, mem, d := newBackendContext(t)
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		origin := &node.Struct{
			BaseNode: node.BaseNode{
				SourcePos: position.Pos{File: "x/origin.go"},
			},
			Name: "Origin", Package: "x",
		}
		file := &emit.File{Name: "x.go", Dir: "x", Package: "x"}
		_ = file.Init().Append(&emit.Stmt{
			BaseEmit: emit.BaseEmit{OriginNode: origin},
		}, emit.Provenance{SetBy: "registrygen"})
		addEmitPackage(t, ctx, &emit.Package{
			Name: "x", Path: "x", Dir: "x",
			Files: []*emit.File{file},
		})
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    x/origin.go\n") {
			t.Fatalf("Source line should aggregate slot-item Origins; got:\n%s", body)
		}
	})

	t.Run("empty SourceRoot leaves the path unchanged", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		// Forward-slashed input — already in the canonical form so
		// no rewriting is expected. The assertion pins the empty-
		// SourceRoot pass-through path.
		addEmitPackage(t, ctx, emitPackage(
			"x",
			structWithOrigin("X", "x", target, "/home/dev/proj/internal/users/user.go"),
		))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Source:    /home/dev/proj/internal/users/user.go\n") {
			t.Fatalf("empty SourceRoot should pass paths through verbatim; got:\n%s", body)
		}
	})
}

// TestHeader_Plugins covers the Plugins: line — registered-order,
// joined by ", ", with optional Version() appended when the plugin
// satisfies [plugin.Versioned].
func TestHeader_Plugins(t *testing.T) {
	t.Parallel()

	t.Run("Plugins line lists every plugin in registration order with version", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Plugins = []plugin.Plugin{
			stubPluginVersion{name: "first", version: "1.0.0"},
			stubPluginVersion{name: "second", version: "0.5.0"},
		}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Plugins:   first 1.0.0, second 0.5.0\n") {
			t.Fatalf("Plugins line mismatched; got:\n%s", body)
		}
	})

	t.Run("plugin without Versioned renders Name only", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Plugins = []plugin.Plugin{stubPluginNoVersion{name: "bare"}}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Plugins:   bare\n") {
			t.Fatalf("plugin without Versioned should render bare name; got:\n%s", body)
		}
	})

	t.Run("plugin with empty Version() renders Name only", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Plugins = []plugin.Plugin{stubPluginVersion{name: "blank", version: ""}}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Plugins:   blank\n") {
			t.Fatalf("plugin with empty version should render Name only; got:\n%s", body)
		}
	})
}

// TestHeader_Command covers the Command: line — verbatim from
// [plugin.BackendContext.Command], whitespace-trimmed; omitted
// when the value is empty after trimming.
func TestHeader_Command(t *testing.T) {
	t.Parallel()

	t.Run("Command line renders the supplied invocation verbatim", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Command = "eidos run --target=foo"
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.Contains(string(body), "// Command:   eidos run --target=foo\n") {
			t.Fatalf("Command line mismatched; got:\n%s", body)
		}
	})

	t.Run("whitespace-only Command is omitted", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Command = "  \t  "
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if strings.Contains(string(body), "Command:") {
			t.Fatalf("whitespace-only Command should be omitted; got:\n%s", body)
		}
	})
}

// TestHeader_Brand covers the tool-identifier customisation slot.
// Library embedders set [plugin.BackendContext.Brand] to their own
// generator name; the standard header / footer markers substitute
// it in place of "eidos" while staying compliant with Go's
// generated-file detection regex.
func TestHeader_Brand(t *testing.T) {
	t.Parallel()

	t.Run("custom Brand substitutes into the DO NOT EDIT marker", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Brand = "acmegen"
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.HasPrefix(string(body), "// Code generated by acmegen. DO NOT EDIT.\n") {
			t.Fatalf("custom Brand should appear in the header marker; got:\n%s", body)
		}
		if !strings.Contains(string(body), "// acmegen: end of generated content.\n") {
			t.Fatalf("custom Brand should appear in the EOGC footer line; got:\n%s", body)
		}
	})

	t.Run("custom Brand keeps the Go-generated-file regex compliant", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Brand = "internal-tool v2"
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		marker := "// Code generated by internal-tool v2. DO NOT EDIT.\n"
		if !strings.HasPrefix(string(body), marker) {
			t.Fatalf("brand with spaces should render verbatim; got:\n%s", body)
		}
	})

	t.Run("empty Brand defaults to 'eidos'", func(t *testing.T) {
		t.Parallel()
		body := renderSingleFieldStruct(t, "F", emit.Builtin("int"))
		if !strings.HasPrefix(body, "// Code generated by eidos. DO NOT EDIT.\n") {
			t.Fatalf("empty Brand should default to 'eidos'; got first line:\n%s", firstLine(body))
		}
		if !strings.Contains(body, "// eidos: end of generated content.\n") {
			t.Fatalf("empty Brand should default in footer too; got:\n%s", body)
		}
	})
}

// TestHeader_PrefixSuffix covers the configurable extension slots:
// HeaderPrefix renders before the DO NOT EDIT marker (with a blank
// line separating it from the standard block); HeaderSuffix
// renders after the Source/Plugins/Command block (before the
// trailing blank line).
func TestHeader_PrefixSuffix(t *testing.T) {
	t.Parallel()

	t.Run("HeaderPrefix lines render before the DO NOT EDIT marker", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.HeaderPrefix = []string{
			"// Copyright 2026 Acme.",
			"// SPDX-License-Identifier: MIT",
		}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		want := "// Copyright 2026 Acme.\n// SPDX-License-Identifier: MIT\n\n// Code generated by eidos. DO NOT EDIT.\n"
		if !strings.HasPrefix(string(body), want) {
			t.Fatalf("output should start with prefix + blank + DO NOT EDIT; got:\n%s", body)
		}
	})

	t.Run("HeaderPrefix renders entries verbatim — supports build directives", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.HeaderPrefix = []string{"//go:build linux"}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		if !strings.HasPrefix(string(body), "//go:build linux\n\n// Code generated by eidos.") {
			t.Fatalf("output should start with the build directive; got:\n%s", body)
		}
	})

	t.Run("HeaderSuffix lines render after the standard block", func(t *testing.T) {
		t.Parallel()
		ctx, mem, d := newBackendContext(t)
		ctx.Command = "eidos run"
		ctx.HeaderSuffix = []string{"// Reviewed-By: platform-team"}
		target := emit.Target{Dir: "x", Filename: "x.go", Package: "x"}
		addEmitPackage(t, ctx, emitPackage("x", emitStructWithFields(
			"x", "X", target,
			fieldSpec{name: "F", builtin: "int"},
		)))
		body := assertRenderSucceeds(t, ctx, mem, d, target)
		want := "// Command:   eidos run\n// Reviewed-By: platform-team\n"
		if !strings.Contains(string(body), want) {
			t.Fatalf("HeaderSuffix should follow the standard block; got:\n%s", body)
		}
	})

	t.Run("empty Prefix/Suffix preserves the bare header layout", func(t *testing.T) {
		t.Parallel()
		body := renderSingleFieldStruct(t, "F", emit.Builtin("int"))
		// Entities without origin surface the "unknown" Source
		// marker — the bare header carries DO NOT EDIT + the
		// unknown marker + a trailing blank line.
		want := "// Code generated by eidos. DO NOT EDIT.\n//\n// Source:    unknown\n\n"
		if !strings.HasPrefix(body, want) {
			t.Fatalf("bare header should start with DO NOT EDIT + unknown source + blank line; got:\n%s", body)
		}
	})
}

// firstLine returns the leading line of s, without the trailing
// newline. Used for legible "expected this prefix" failure
// messages.
func firstLine(s string) string {
	if head, _, ok := strings.Cut(s, "\n"); ok {
		return head
	}
	return s
}
